AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the snyk-monitor helm chart into an existing kubernetes cluster (qs-)"
Parameters:
  HelmLambdaArn:
    Type: String
  KubeConfigPath:
    Type: String
  KubeConfigKmsContext:
    Type: String
    Default: "EKSQuickStart"
  KubeClusterName:
    Type: String
  SnykIntegrationId:
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
Resources:
  SnykNamespace:
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeManifestLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Manifest:
        kind: Namespace
        apiVersion: v1
        metadata:
          name: snyk-monitor
  SnykSecret:
    Type: "Custom::KubeManifest"
    DependsOn: SnykNamespace
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeManifestLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Manifest:
        kind: Secret
        apiVersion: v1
        metadata:
          name: snyk-monitor
          namespace: snyk-monitor
        type: Opaque
        data:
          dockercfg.json: {}
          integrationId: !Ref SnykIntegrationId
  SnykHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: SnykSecret
    Properties:
      ClusterID: !Ref KubeClusterName
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Repository: https://snyk.github.io/kubernetes-monitor/
      Namespace: snyk-monitor
      Chart: snyk-charts/snyk-monitor
      Name: snyk-monitor
      Values:
        server.persistentVolume.storageClass: "gp2"
        server.statefulSet.enabled: true
        server.replicaCount: 2
        server.service.sessionAffinity: ClientIP
        alertmanager.persistentVolume.storageClass: "gp2"
        alertmanager.statefulSet.enabled: true
        alertmanager.replicaCount: 2
Outputs:
  SnykReleaseName:
    Value: !Ref SnykHelmChart